"""improve users security

Revision ID: 574391fde96e
Revises: 4e330617525f
Create Date: 2026-07-27 15:03:39.977970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '574391fde96e'
down_revision: Union[str, Sequence[str], None] = '4e330617525f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('senha_hash', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('users', 'ativo',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'criado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('users_login_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_login'), 'users', ['login'], unique=True)
    op.drop_column('users', 'senha')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('senha', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_login'), table_name='users')
    op.create_unique_constraint(op.f('users_login_key'), 'users', ['login'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'criado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'ativo',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('users', 'atualizado_em')
    op.drop_column('users', 'senha_hash')
    # ### end Alembic commands ###
