"""create finance module

Revision ID: 5b4b728e0f72
Revises: 7ad0c123d91c
Create Date: 2026-07-30 17:41:08.061341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b4b728e0f72'
down_revision: Union[str, Sequence[str], None] = '7ad0c123d91c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_methods_id'), 'payment_methods', ['id'], unique=False)
    op.create_index(op.f('ix_payment_methods_nome'), 'payment_methods', ['nome'], unique=True)
    op.create_table('cash_flow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('origem', sa.String(length=20), nullable=False),
    sa.Column('reference_type', sa.String(length=60), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('performed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("origem IN ('VENDA', 'DESPESA', 'COMISSAO', 'AJUSTE')", name='ck_cash_flow_valid_origin'),
    sa.CheckConstraint("tipo IN ('ENTRADA', 'SAIDA')", name='ck_cash_flow_valid_type'),
    sa.CheckConstraint('valor > 0', name='ck_cash_flow_amount_positive'),
    sa.ForeignKeyConstraint(['performed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_flow_criado_em'), 'cash_flow', ['criado_em'], unique=False)
    op.create_index(op.f('ix_cash_flow_id'), 'cash_flow', ['id'], unique=False)
    op.create_index(op.f('ix_cash_flow_origem'), 'cash_flow', ['origem'], unique=False)
    op.create_index(op.f('ix_cash_flow_performed_by_user_id'), 'cash_flow', ['performed_by_user_id'], unique=False)
    op.create_index(op.f('ix_cash_flow_reference_id'), 'cash_flow', ['reference_id'], unique=False)
    op.create_index(op.f('ix_cash_flow_reference_type'), 'cash_flow', ['reference_type'], unique=False)
    op.create_index(op.f('ix_cash_flow_tipo'), 'cash_flow', ['tipo'], unique=False)
    op.create_table('accounts_receivable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('numero_parcela', sa.Integer(), nullable=False),
    sa.Column('total_parcelas', sa.Integer(), nullable=False),
    sa.Column('valor_original', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('valor_recebido', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('saldo_restante', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='PENDENTE', nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('criado_por_user_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PENDENTE', 'PARCIAL', 'PAGO', 'CANCELADO')", name='ck_accounts_receivable_valid_status'),
    sa.CheckConstraint('numero_parcela <= total_parcelas', name='ck_accounts_receivable_installment_within_total'),
    sa.CheckConstraint('numero_parcela > 0', name='ck_accounts_receivable_installment_positive'),
    sa.CheckConstraint('saldo_restante >= 0', name='ck_accounts_receivable_remaining_amount_nonnegative'),
    sa.CheckConstraint('total_parcelas > 0', name='ck_accounts_receivable_total_installments_positive'),
    sa.CheckConstraint('valor_original > 0', name='ck_accounts_receivable_original_amount_positive'),
    sa.CheckConstraint('valor_recebido + saldo_restante = valor_original', name='ck_accounts_receivable_amount_balance'),
    sa.CheckConstraint('valor_recebido >= 0', name='ck_accounts_receivable_received_amount_nonnegative'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['criado_por_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sale_id', 'numero_parcela', name='uq_accounts_receivable_sale_installment')
    )
    op.create_index(op.f('ix_accounts_receivable_client_id'), 'accounts_receivable', ['client_id'], unique=False)
    op.create_index(op.f('ix_accounts_receivable_codigo'), 'accounts_receivable', ['codigo'], unique=True)
    op.create_index(op.f('ix_accounts_receivable_criado_por_user_id'), 'accounts_receivable', ['criado_por_user_id'], unique=False)
    op.create_index(op.f('ix_accounts_receivable_data_vencimento'), 'accounts_receivable', ['data_vencimento'], unique=False)
    op.create_index(op.f('ix_accounts_receivable_id'), 'accounts_receivable', ['id'], unique=False)
    op.create_index(op.f('ix_accounts_receivable_sale_id'), 'accounts_receivable', ['sale_id'], unique=False)
    op.create_index(op.f('ix_accounts_receivable_status'), 'accounts_receivable', ['status'], unique=False)
    op.create_table('accounts_receivable_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_receivable_id', sa.Integer(), nullable=False),
    sa.Column('status_anterior', sa.String(length=20), nullable=True),
    sa.Column('status_novo', sa.String(length=20), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('performed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status_anterior IS NULL OR status_anterior IN ('PENDENTE', 'PARCIAL', 'PAGO', 'CANCELADO')", name='ck_accounts_receivable_history_valid_previous_status'),
    sa.CheckConstraint("status_novo IN ('PENDENTE', 'PARCIAL', 'PAGO', 'CANCELADO')", name='ck_accounts_receivable_history_valid_new_status'),
    sa.ForeignKeyConstraint(['account_receivable_id'], ['accounts_receivable.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_receivable_history_account_receivable_id'), 'accounts_receivable_history', ['account_receivable_id'], unique=False)
    op.create_index(op.f('ix_accounts_receivable_history_criado_em'), 'accounts_receivable_history', ['criado_em'], unique=False)
    op.create_index(op.f('ix_accounts_receivable_history_id'), 'accounts_receivable_history', ['id'], unique=False)
    op.create_index(op.f('ix_accounts_receivable_history_performed_by_user_id'), 'accounts_receivable_history', ['performed_by_user_id'], unique=False)
    op.create_index(op.f('ix_accounts_receivable_history_status_novo'), 'accounts_receivable_history', ['status_novo'], unique=False)
    op.create_table('accounts_receivable_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_receivable_id', sa.Integer(), nullable=False),
    sa.Column('payment_method_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('data_pagamento', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('recebido_por_user_id', sa.Integer(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('valor > 0', name='ck_accounts_receivable_payments_amount_positive'),
    sa.ForeignKeyConstraint(['account_receivable_id'], ['accounts_receivable.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recebido_por_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_receivable_payments_account_receivable_id'), 'accounts_receivable_payments', ['account_receivable_id'], unique=False)
    op.create_index(op.f('ix_accounts_receivable_payments_data_pagamento'), 'accounts_receivable_payments', ['data_pagamento'], unique=False)
    op.create_index(op.f('ix_accounts_receivable_payments_id'), 'accounts_receivable_payments', ['id'], unique=False)
    op.create_index(op.f('ix_accounts_receivable_payments_payment_method_id'), 'accounts_receivable_payments', ['payment_method_id'], unique=False)
    op.create_index(op.f('ix_accounts_receivable_payments_recebido_por_user_id'), 'accounts_receivable_payments', ['recebido_por_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounts_receivable_payments_recebido_por_user_id'), table_name='accounts_receivable_payments')
    op.drop_index(op.f('ix_accounts_receivable_payments_payment_method_id'), table_name='accounts_receivable_payments')
    op.drop_index(op.f('ix_accounts_receivable_payments_id'), table_name='accounts_receivable_payments')
    op.drop_index(op.f('ix_accounts_receivable_payments_data_pagamento'), table_name='accounts_receivable_payments')
    op.drop_index(op.f('ix_accounts_receivable_payments_account_receivable_id'), table_name='accounts_receivable_payments')
    op.drop_table('accounts_receivable_payments')
    op.drop_index(op.f('ix_accounts_receivable_history_status_novo'), table_name='accounts_receivable_history')
    op.drop_index(op.f('ix_accounts_receivable_history_performed_by_user_id'), table_name='accounts_receivable_history')
    op.drop_index(op.f('ix_accounts_receivable_history_id'), table_name='accounts_receivable_history')
    op.drop_index(op.f('ix_accounts_receivable_history_criado_em'), table_name='accounts_receivable_history')
    op.drop_index(op.f('ix_accounts_receivable_history_account_receivable_id'), table_name='accounts_receivable_history')
    op.drop_table('accounts_receivable_history')
    op.drop_index(op.f('ix_accounts_receivable_status'), table_name='accounts_receivable')
    op.drop_index(op.f('ix_accounts_receivable_sale_id'), table_name='accounts_receivable')
    op.drop_index(op.f('ix_accounts_receivable_id'), table_name='accounts_receivable')
    op.drop_index(op.f('ix_accounts_receivable_data_vencimento'), table_name='accounts_receivable')
    op.drop_index(op.f('ix_accounts_receivable_criado_por_user_id'), table_name='accounts_receivable')
    op.drop_index(op.f('ix_accounts_receivable_codigo'), table_name='accounts_receivable')
    op.drop_index(op.f('ix_accounts_receivable_client_id'), table_name='accounts_receivable')
    op.drop_table('accounts_receivable')
    op.drop_index(op.f('ix_cash_flow_tipo'), table_name='cash_flow')
    op.drop_index(op.f('ix_cash_flow_reference_type'), table_name='cash_flow')
    op.drop_index(op.f('ix_cash_flow_reference_id'), table_name='cash_flow')
    op.drop_index(op.f('ix_cash_flow_performed_by_user_id'), table_name='cash_flow')
    op.drop_index(op.f('ix_cash_flow_origem'), table_name='cash_flow')
    op.drop_index(op.f('ix_cash_flow_id'), table_name='cash_flow')
    op.drop_index(op.f('ix_cash_flow_criado_em'), table_name='cash_flow')
    op.drop_table('cash_flow')
    op.drop_index(op.f('ix_payment_methods_nome'), table_name='payment_methods')
    op.drop_index(op.f('ix_payment_methods_id'), table_name='payment_methods')
    op.drop_table('payment_methods')
    # ### end Alembic commands ###
