"""create sales module

Revision ID: 7ad0c123d91c
Revises: f37fde6a14e9
Create Date: 2026-07-28 15:16:55.764598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ad0c123d91c'
down_revision: Union[str, Sequence[str], None] = 'f37fde6a14e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='AGUARDANDO_CONFIRMACAO', nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('desconto', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('criado_por_user_id', sa.Integer(), nullable=False),
    sa.Column('confirmado_por_user_id', sa.Integer(), nullable=True),
    sa.Column('cancelado_por_user_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('confirmado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelado_em', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('AGUARDANDO_CONFIRMACAO', 'CONFIRMADA', 'CANCELADA')", name='ck_sales_valid_status'),
    sa.CheckConstraint('desconto <= subtotal', name='ck_sales_discount_not_greater_than_subtotal'),
    sa.CheckConstraint('desconto >= 0', name='ck_sales_discount_non_negative'),
    sa.CheckConstraint('subtotal >= 0', name='ck_sales_subtotal_non_negative'),
    sa.CheckConstraint('total >= 0', name='ck_sales_total_non_negative'),
    sa.ForeignKeyConstraint(['cancelado_por_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['confirmado_por_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['criado_por_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_cancelado_por_user_id'), 'sales', ['cancelado_por_user_id'], unique=False)
    op.create_index(op.f('ix_sales_client_id'), 'sales', ['client_id'], unique=False)
    op.create_index(op.f('ix_sales_codigo'), 'sales', ['codigo'], unique=True)
    op.create_index(op.f('ix_sales_confirmado_por_user_id'), 'sales', ['confirmado_por_user_id'], unique=False)
    op.create_index(op.f('ix_sales_criado_por_user_id'), 'sales', ['criado_por_user_id'], unique=False)
    op.create_index(op.f('ix_sales_id'), 'sales', ['id'], unique=False)
    op.create_index(op.f('ix_sales_seller_id'), 'sales', ['seller_id'], unique=False)
    op.create_index(op.f('ix_sales_status'), 'sales', ['status'], unique=False)
    op.create_table('sale_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('codigo_produto', sa.String(length=20), nullable=False),
    sa.Column('nome_produto', sa.String(length=120), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('preco_unitario >= 0', name='ck_sale_items_unit_price_non_negative'),
    sa.CheckConstraint('quantidade > 0', name='ck_sale_items_quantity_positive'),
    sa.CheckConstraint('subtotal >= 0', name='ck_sale_items_subtotal_non_negative'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sale_id', 'product_id', name='uq_sale_items_sale_product')
    )
    op.create_index(op.f('ix_sale_items_id'), 'sale_items', ['id'], unique=False)
    op.create_index(op.f('ix_sale_items_product_id'), 'sale_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_sale_items_sale_id'), 'sale_items', ['sale_id'], unique=False)
    op.create_table('sale_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('status_anterior', sa.String(length=30), nullable=True),
    sa.Column('status_novo', sa.String(length=30), nullable=False),
    sa.Column('performed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status_anterior IS NULL OR status_anterior IN ('AGUARDANDO_CONFIRMACAO', 'CONFIRMADA', 'CANCELADA')", name='ck_sale_status_history_valid_previous_status'),
    sa.CheckConstraint("status_novo IN ('AGUARDANDO_CONFIRMACAO', 'CONFIRMADA', 'CANCELADA')", name='ck_sale_status_history_valid_new_status'),
    sa.ForeignKeyConstraint(['performed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_status_history_criado_em'), 'sale_status_history', ['criado_em'], unique=False)
    op.create_index(op.f('ix_sale_status_history_id'), 'sale_status_history', ['id'], unique=False)
    op.create_index(op.f('ix_sale_status_history_performed_by_user_id'), 'sale_status_history', ['performed_by_user_id'], unique=False)
    op.create_index(op.f('ix_sale_status_history_sale_id'), 'sale_status_history', ['sale_id'], unique=False)
    op.create_index(op.f('ix_sale_status_history_status_novo'), 'sale_status_history', ['status_novo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sale_status_history_status_novo'), table_name='sale_status_history')
    op.drop_index(op.f('ix_sale_status_history_sale_id'), table_name='sale_status_history')
    op.drop_index(op.f('ix_sale_status_history_performed_by_user_id'), table_name='sale_status_history')
    op.drop_index(op.f('ix_sale_status_history_id'), table_name='sale_status_history')
    op.drop_index(op.f('ix_sale_status_history_criado_em'), table_name='sale_status_history')
    op.drop_table('sale_status_history')
    op.drop_index(op.f('ix_sale_items_sale_id'), table_name='sale_items')
    op.drop_index(op.f('ix_sale_items_product_id'), table_name='sale_items')
    op.drop_index(op.f('ix_sale_items_id'), table_name='sale_items')
    op.drop_table('sale_items')
    op.drop_index(op.f('ix_sales_status'), table_name='sales')
    op.drop_index(op.f('ix_sales_seller_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_criado_por_user_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_confirmado_por_user_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_codigo'), table_name='sales')
    op.drop_index(op.f('ix_sales_client_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_cancelado_por_user_id'), table_name='sales')
    op.drop_table('sales')
    # ### end Alembic commands ###
