"""create purchase module
Revision ID: a13c9e7d41b2
Revises: 5b4b728e0f72
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
revision: str = "a13c9e7d41b2"
down_revision: Union[str, Sequence[str], None] = "5b4b728e0f72"
branch_labels = None
depends_on = None

def upgrade() -> None:
    op.create_table("suppliers",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("nome",sa.String(120),nullable=False),sa.Column("documento",sa.String(20),nullable=True),sa.Column("email",sa.String(150)),sa.Column("telefone",sa.String(30)),sa.Column("observacao",sa.Text()),sa.Column("ativo",sa.Boolean(),server_default=sa.text("true"),nullable=False),sa.Column("criado_em",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column("atualizado_em",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.UniqueConstraint("documento"))
    op.create_index("ix_suppliers_id","suppliers",["id"]); op.create_index("ix_suppliers_nome","suppliers",["nome"]); op.create_index("ix_suppliers_documento","suppliers",["documento"])
    op.create_table("purchases",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("codigo",sa.String(20),nullable=False),sa.Column("supplier_id",sa.Integer(),sa.ForeignKey("suppliers.id",ondelete="RESTRICT"),nullable=False),sa.Column("status",sa.String(30),server_default="AGUARDANDO_CONFIRMACAO",nullable=False),sa.Column("subtotal",sa.Numeric(12,2),server_default="0",nullable=False),sa.Column("desconto",sa.Numeric(12,2),server_default="0",nullable=False),sa.Column("frete",sa.Numeric(12,2),server_default="0",nullable=False),sa.Column("total",sa.Numeric(12,2),server_default="0",nullable=False),sa.Column("observacao",sa.Text()),sa.Column("criado_por_user_id",sa.Integer(),sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False),sa.Column("confirmado_por_user_id",sa.Integer(),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("cancelado_por_user_id",sa.Integer(),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("criado_em",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column("atualizado_em",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column("confirmado_em",sa.DateTime(timezone=True)),sa.Column("cancelado_em",sa.DateTime(timezone=True)),sa.CheckConstraint("subtotal >= 0",name="ck_purchases_subtotal_non_negative"),sa.CheckConstraint("desconto >= 0",name="ck_purchases_discount_non_negative"),sa.CheckConstraint("frete >= 0",name="ck_purchases_freight_non_negative"),sa.CheckConstraint("total >= 0",name="ck_purchases_total_non_negative"),sa.CheckConstraint("desconto <= subtotal",name="ck_purchases_discount_not_greater_than_subtotal"),sa.CheckConstraint("status IN ('AGUARDANDO_CONFIRMACAO','CONFIRMADA','CANCELADA')",name="ck_purchases_valid_status"),sa.UniqueConstraint("codigo"))
    for c in ["id","codigo","supplier_id","status","criado_por_user_id","confirmado_por_user_id","cancelado_por_user_id"]: op.create_index(f"ix_purchases_{c}","purchases",[c])
    op.create_table("purchase_items",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("purchase_id",sa.Integer(),sa.ForeignKey("purchases.id",ondelete="CASCADE"),nullable=False),sa.Column("product_id",sa.Integer(),sa.ForeignKey("products.id",ondelete="RESTRICT"),nullable=False),sa.Column("codigo_produto",sa.String(20),nullable=False),sa.Column("nome_produto",sa.String(120),nullable=False),sa.Column("quantidade",sa.Integer(),nullable=False),sa.Column("custo_unitario",sa.Numeric(12,2),nullable=False),sa.Column("subtotal",sa.Numeric(12,2),nullable=False),sa.Column("criado_em",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.CheckConstraint("quantidade > 0",name="ck_purchase_items_quantity_positive"),sa.CheckConstraint("custo_unitario >= 0",name="ck_purchase_items_cost_non_negative"),sa.UniqueConstraint("purchase_id","product_id",name="uq_purchase_items_purchase_product"))
    op.create_index("ix_purchase_items_id","purchase_items",["id"]); op.create_index("ix_purchase_items_purchase_id","purchase_items",["purchase_id"]); op.create_index("ix_purchase_items_product_id","purchase_items",["product_id"])
    op.create_table("purchase_status_history",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("purchase_id",sa.Integer(),sa.ForeignKey("purchases.id",ondelete="CASCADE"),nullable=False),sa.Column("status_anterior",sa.String(30)),sa.Column("status_novo",sa.String(30),nullable=False),sa.Column("performed_by_user_id",sa.Integer(),sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False),sa.Column("observacao",sa.Text()),sa.Column("criado_em",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False))
    op.create_index("ix_purchase_status_history_id","purchase_status_history",["id"]); op.create_index("ix_purchase_status_history_purchase_id","purchase_status_history",["purchase_id"]); op.create_index("ix_purchase_status_history_performed_by_user_id","purchase_status_history",["performed_by_user_id"])
    op.execute("INSERT INTO system_sequences (nome, prefixo, tamanho, ultimo_numero) VALUES ('PURCHASE','COM',6,0) ON CONFLICT (nome) DO NOTHING")

def downgrade() -> None:
    op.execute("DELETE FROM system_sequences WHERE nome='PURCHASE'")
    op.drop_table("purchase_status_history"); op.drop_table("purchase_items"); op.drop_table("purchases"); op.drop_table("suppliers")
